package main

const (
	NETWORK_SERVER_ID = 0x7428
	NETWORK_CLIENT_ID = 0xdef6

	NETPLAYER_TYPE_PLAYER1  = 0
	NETPLAYER_TYPE_PLAYER2  = 1
	NETPLAYER_TYPE_PLAYER3  = 2
	NETPLAYER_TYPE_PLAYER4  = 3
	NETPLAYER_TYPE_PLAYER5  = 4
	NETPLAYER_TYPE_PLAYER6  = 5
	NETPLAYER_TYPE_OBSERVER = 7

	CTOS_RESPONSE      = 0x1
	CTOS_UPDATE_DECK   = 0x2
	CTOS_HAND_RESULT   = 0x3
	CTOS_TP_RESULT     = 0x4
	CTOS_PLAYER_INFO   = 0x10
	CTOS_CREATE_GAME   = 0x11
	CTOS_JOIN_GAME     = 0x12
	CTOS_LEAVE_GAME    = 0x13
	CTOS_SURRENDER     = 0x14
	CTOS_TIME_CONFIRM  = 0x15
	CTOS_CHAT          = 0x16
	CTOS_HS_TODUELIST  = 0x20
	CTOS_HS_TOOBSERVER = 0x21
	CTOS_HS_READY      = 0x22
	CTOS_HS_NOTREADY   = 0x23
	CTOS_HS_KICK       = 0x24
	CTOS_HS_START      = 0x25

	STOC_GAME_MSG         = 0x1
	STOC_ERROR_MSG        = 0x2
	STOC_SELECT_HAND      = 0x3
	STOC_SELECT_TP        = 0x4
	STOC_HAND_RESULT      = 0x5
	STOC_TP_RESULT        = 0x6
	STOC_CHANGE_SIDE      = 0x7
	STOC_WAITING_SIDE     = 0x8
	STOC_DECK_COUNT       = 0x9
	STOC_CREATE_GAME      = 0x11
	STOC_JOIN_GAME        = 0x12
	STOC_TYPE_CHANGE      = 0x13
	STOC_LEAVE_GAME       = 0x14
	STOC_DUEL_START       = 0x15
	STOC_DUEL_END         = 0x16
	STOC_REPLAY           = 0x17
	STOC_TIME_LIMIT       = 0x18
	STOC_CHAT             = 0x19
	STOC_HS_PLAYER_ENTER  = 0x20
	STOC_HS_PLAYER_CHANGE = 0x21
	STOC_HS_WATCH_CHANGE  = 0x22

	PLAYERCHANGE_OBSERVE  = 0x8
	PLAYERCHANGE_READY    = 0x9
	PLAYERCHANGE_NOTREADY = 0xa
	PLAYERCHANGE_LEAVE    = 0xb

	ERRMSG_JOINERROR = 0x1
	ERRMSG_DECKERROR = 0x2
	ERRMSG_SIDEERROR = 0x3
	ERRMSG_VERERROR  = 0x4

	DECKERROR_LFLIST      = 0x1
	DECKERROR_OCGONLY     = 0x2
	DECKERROR_TCGONLY     = 0x3
	DECKERROR_UNKNOWNCARD = 0x4
	DECKERROR_CARDCOUNT   = 0x5
	DECKERROR_MAINCOUNT   = 0x6
	DECKERROR_EXTRACOUNT  = 0x7
	DECKERROR_SIDECOUNT   = 0x8

	MODE_SINGLE = 0x0
	MODE_MATCH  = 0x1
	MODE_TAG    = 0x2

	DUEL_STAGE_BEGIN   = 0
	DUEL_STAGE_FINGER  = 1
	DUEL_STAGE_FIRSTGO = 2
	DUEL_STAGE_DUELING = 3
	DUEL_STAGE_SIDING  = 4
	DUEL_STAGE_END     = 5
)
